In [ ]:
# Dimensionality Reduction : 
PCA **************
LDA *****
t-SNA
Backward Feature Elimination ******
Forward feature Selection ****
Factor Analysis
Missing value Ratio
Low variance filter
Random Forest
High correlation filter
ICA - Independent Component Analysist
Ridge and lasso
etc......

# When to use 
#1) when huge data there, we have to use dimentions 
    reduction to consider significant variable
#2) Less dimension lead to less tunning / computation 
    time
#3) when we have large dimensions
#4) it handles multicollinarity by removing redundant feature
#5) too many missing value, it will consider signification one and select missing value  into different slice
#6) instead of removing variable, slice the data by the help of "eigen value/matrix" to get significant varielbe


In [1]:
import os
os.chdir("D:\KKK\DSP\Python\Sample data")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
dataset = pd.read_csv("Bank-data.csv")
dataset.head()

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no

In [4]:
dataset['Churn'] = dataset['Churn'].astype('category')

In [5]:
dataset['Churn'] = dataset['Churn'].cat.codes

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          518 non-null    int64  
 1   interest_rate  518 non-null    float64
 2   credit         518 non-null    int64  
 3   Gender         518 non-null    int64  
 4   previous       518 non-null    int64  
 5   duration       518 non-null    int64  
 6   Churn          518 non-null    int8   
dtypes: float64(1), int64(5), int8(1)
memory usage: 24.9 KB


In [7]:
dataset.isnull().sum()
#dataset.isnull().any()

Index            0
interest_rate    0
credit           0
Gender           0
previous         0
duration         0
Churn            0
dtype: int64

In [8]:
dataset.head(10)

Index  interest_rate  credit  Gender  previous  duration  Churn
0      0          1.334       0       1         0       117      0
1      1          0.767       0       0         1       274      1
2      2          4.858       0       1         0       167      0
3      3          4.120       0       0         0       686      1
4      4          4.856       0       1         0       159      0
5      5          0.899       0       0         0       120      0
6      6          4.962       0       0         0       337      0
7      7          4.858       0       1         0       640      0
8      8          4.962       0       0         0       663      1
9      9          4.865       0       0         0       403      0

In [9]:
# slicing the data into dep and ind variable
# x - ind var
# y - dep var

In [10]:
x = dataset.iloc[:,0:6].values
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [11]:
y = dataset.iloc[:,6].values
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [12]:
# Split the data into training and test 
# from sklearn.cross_validation import train_test_split - 2.7 version
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [13]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(414, 6)
(104, 6)
(414,)
(104,)


In [14]:
# Building a Logistic Model with training dataset
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

LogisticRegression()

In [15]:
# predict your model with test dataset
y_pred = logmodel.predict(x_test)

In [16]:
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0], dtype=int8)

In [17]:
# Model evaluation 
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[39,  4],
       [ 5, 56]], dtype=int64)

In [18]:
(39+56)/(39+4+5+56)

0.9134615384615384

# Principal Component Analysis

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components= None) # None - all variables
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [20]:
x_train

array([[281.   ,   1.327,   0.   ,   1.   ,   0.   , 143.   ],
       [414.   ,   4.153,   0.   ,   0.   ,   0.   , 257.   ],
       [ 56.   ,   4.076,   0.   ,   0.   ,   0.   , 147.   ],
       ...,
       [  9.   ,   4.865,   0.   ,   0.   ,   0.   , 403.   ],
       [359.   ,   0.715,   0.   ,   0.   ,   1.   ,  95.   ],
       [192.   ,   1.27 ,   0.   ,   1.   ,   0.   ,  86.   ]])

In [21]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -235.770157   29.660361  1.608825  0.731629 -0.166140 -0.011699
1   -117.692991  159.053279 -1.275379 -0.225469 -0.079910 -0.005317
2   -238.760757 -195.356829 -1.006731 -0.279036 -0.048918 -0.045138
3   -174.503625  -59.285255  2.009055 -0.365301  0.724113 -0.112636
4   -280.616022 -190.054634 -1.905811 -0.274531  0.011216 -0.037383
..          ...         ...       ...       ...       ...       ...
409 -346.273529 -178.009265 -1.934771 -0.274960  0.011227 -0.036729
410 -235.894427   25.662331  1.674134  0.730706 -0.170014 -0.012668
411   15.655879 -250.286915 -1.699724 -0.273828  0.006871 -0.041578
412 -281.324125  109.114416  2.213363 -0.347339  0.686183 -0.098623
413 -295.507338  -57.526006  1.705818  0.717257 -0.160735 -0.022134

[414 rows x 6 columns]

In [22]:
pd.DataFrame(x_test_n)

0           1         2         3         4         5
0    245.695238 -124.926303  2.719485  0.578075  0.239301  0.079582
1   -200.286307 -143.506131 -2.009813 -0.149347 -0.370878 -0.159126
2    -84.716346  -48.700152 -0.801462 -0.295157 -0.304793  0.881284
3    231.098229   -5.306611 -1.491767 -0.247018 -0.337495 -0.123044
4   -113.948833  -81.645147 -1.787535 -0.448594  0.603960 -0.159219
..          ...         ...       ...       ...       ...       ...
99  -174.547600  -15.367468 -1.972121 -0.132799 -0.374086 -0.141970
100  165.276373   82.177751 -0.976310  0.727498 -0.024570  0.004839
101 -100.492637 -205.224922 -1.896996 -0.189385 -0.359211 -0.162549
102  431.025097 -173.787378 -0.472091 -0.354938 -0.257615 -0.114099
103 -348.457368  -91.011533  1.249550 -0.180508 -0.151516 -0.066715

[104 rows x 6 columns]

In [23]:
explained_variance = pca.explained_variance_ratio_
# how many split happen by PCA

In [24]:
explained_variance

array([8.62936527e-01, 1.37041086e-01, 1.99277149e-05, 1.37192544e-06,
       7.54923198e-07, 3.32194392e-07])

In [25]:
# 1st slice = 86.4%
# 2nd slice = 13.7%
# By the help of slicing, we can conclude that PCA1 and PCA2 are giving 99% information
# hence, ready to remove PCA3 to PCA6
# Significant slicing = PCA1 and PCA2


In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components= 2) # all variables
x_train_2 = pca.fit_transform(x_train)
x_test_2 = pca.fit_transform(x_test)

In [27]:
pd.DataFrame(x_train_2)

0           1
0   -235.770157   29.660361
1   -117.692991  159.053279
2   -238.760757 -195.356829
3   -174.503625  -59.285255
4   -280.616022 -190.054634
..          ...         ...
409 -346.273529 -178.009265
410 -235.894427   25.662331
411   15.655879 -250.286915
412 -281.324125  109.114416
413 -295.507338  -57.526006

[414 rows x 2 columns]

In [28]:
pd.DataFrame(x_test_2)

0           1
0    245.695238 -124.926303
1   -200.286307 -143.506131
2    -84.716346  -48.700152
3    231.098229   -5.306611
4   -113.948833  -81.645147
..          ...         ...
99  -174.547600  -15.367468
100  165.276373   82.177751
101 -100.492637 -205.224922
102  431.025097 -173.787378
103 -348.457368  -91.011533

[104 rows x 2 columns]

In [29]:
from sklearn.linear_model import LogisticRegression
logmodel1 = LogisticRegression()
logmodel1.fit(x_train_2, y_train)

LogisticRegression()

In [30]:
y_pred_pca = logmodel1.predict(x_test_2)

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_pca)

array([[38,  5],
       [29, 32]], dtype=int64)

In [32]:
(39+32)/(39+4+29+32)

0.6826923076923077

In [33]:
!pip install xgboost

In [35]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train_2, y_train)

C:\Users\kanna\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:53:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [36]:
y_pred_xgb = classifier.predict(x_test_2)

In [37]:
confusion_matrix(y_test, y_pred_xgb)

array([[34,  9],
       [20, 41]], dtype=int64)

In [38]:
(35+41)/(35+8+20+41)

0.7307692307692307

In [39]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator= classifier, 
                           X=x_train_2, y=y_train, cv=15)
accuracy

C:\Users\kanna\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:53:31] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:53:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:53:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:53:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

array([0.64285714, 0.71428571, 0.53571429, 0.57142857, 0.5       ,
       0.75      , 0.46428571, 0.57142857, 0.57142857, 0.74074074,
       0.7037037 , 0.62962963, 0.74074074, 0.62962963, 0.51851852])

In [40]:
accuracy[9]

0.7407407407407407

# Eigen values and Eigen Vectors

In [41]:
step1 : (A-lambda*I)*X = 0
    # A - given matrix
    # Lambda - Constant matrix
    # I - Identity matrxi
    # X - Unknown matrix
    # 0 - null matrxi

Step2 : (Lambda)**3-[Sum of diagonal element]*(Lambda)**2
    + [Sum of diagonal minor]*lambda 
        -|A| = 0

Step3 : Crammer's rule
    
this maths belongs in PCA concept

SyntaxError: invalid syntax (<ipython-input-41-a4dcbce7d4df>, line 1)